[workspace]
resolver = "2"

members = [
    "contracts/solution"
]

[workspace.dependencies.soroban-sdk]
version = "0.6.0"

[profile.release]
opt-level = 3
overflow-checks = false
debug = 0
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true